---
title: "*Chamaetylas poliophrys*"
author: "Peggy Huss & Jacob C. Cooper"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r}
library(tidyverse)
```


# PCA Results

Directions from [this site](https://speciationgenomics.github.io/pca/).

```{r}
pca <- read_table("~/Documents/06_plink/chamaetylas_nothin_plink_pca.eigenvec",
                  col_names = F)
eigenval <- scan("~/Documents/06_plink/chamaetylas_nothin_plink_pca.eigenval")
```

```{r}
# sort out the pca data
# remove nuisance column
pca <- pca[,-1]
# set names
names(pca)[1] <- "ind"
names(pca)[2:ncol(pca)] <- paste0("PC", 1:(ncol(pca)-1))
```

```{r}
# sort out the individual species and pops
# region
region <- rep(NA, length(pca$ind))

region[grep("FMNH346401", pca$ind)] <- "East"
region[grep("FMNH355643", pca$ind)] <- "East"
region[grep("FMNH385038", pca$ind)] <- "East"
region[grep("FMNH443853", pca$ind)] <- "West"
region[grep("FMNH443854", pca$ind)] <- "West"
region[grep("FMNH443856", pca$ind)] <- "West"
region[grep("FMNH450510", pca$ind)] <- "West"
region[grep("FMNH450511", pca$ind)] <- "West"
region[grep("FMNH450512", pca$ind)] <- "West"

# location
loc <- rep(NA, length(pca$ind))

loc[grep("FMNH346401", pca$ind)] <- "Kibira-Nyungwe"
loc[grep("FMNH355643", pca$ind)] <- "Rwenzori"
loc[grep("FMNH385038", pca$ind)] <- "Bwindi"
loc[grep("FMNH443853", pca$ind)] <- "Kahuzi-Biega"
loc[grep("FMNH443854", pca$ind)] <- "Kahuzi-Biega"
loc[grep("FMNH443856", pca$ind)] <- "Kahuzi-Biega"
loc[grep("FMNH450510", pca$ind)] <- "Kabogo"
loc[grep("FMNH450511", pca$ind)] <- "Kabogo"
loc[grep("FMNH450512", pca$ind)] <- "Kabogo"

# from tutorial - species_location
# combine - if you want to plot each in different colours
# spp_loc <- paste0(spp, "_", loc)
```

```{r}
# remake data.frame
pca <- as_tibble(data.frame(pca, loc, region))
```

```{r}
# first convert to percentage variance explained
pve <- data.frame(PC = 1:length(eigenval), pve = eigenval/sum(eigenval)*100)
```

```{r}
# make plot
a <- ggplot(pve, aes(PC, pve)) + geom_bar(stat = "identity")
a + ylab("Percentage variance explained") + theme_light()
```

```{r}
# calculate the cumulative sum of the percentage variance explained
cumsum(pve$pve)
```

```{r}
# plot pca
# color brewer colorblind friendly palette
b <- ggplot(pca, aes(PC1, PC2, col = region, shape = loc)) + 
  geom_point(size = 3) + 
  scale_colour_manual(values = c("#1b9e77", "#d95f02", "#7570b3")) +
  coord_equal() + 
  theme_light() + 
  xlab(paste0("PC1 (", signif(pve$pve[1], 3), "%)")) + 
  ylab(paste0("PC2 (", signif(pve$pve[2], 3), "%)")) +
  ggtitle("PC 1 + PC 2")

print(b)
```

```{r}
# plot pca
# color brewer colorblind friendly palette
b <- ggplot(pca, aes(PC2, PC3, col = region, shape = loc)) + 
  geom_point(size = 3) + 
  scale_colour_manual(values = c("#1b9e77", "#d95f02", "#7570b3")) +
  coord_equal() + 
  theme_light() + 
  xlab(paste0("PC2 (", signif(pve$pve[1], 3), "%)")) + 
  ylab(paste0("PC3 (", signif(pve$pve[2], 3), "%)")) +
  ggtitle("PC 2 + PC 3")

print(b)
```

```{r}
# plot pca
# color brewer colorblind friendly palette
b <- ggplot(pca, aes(PC1, PC3, col = region, shape = loc)) + 
  geom_point(size = 3) + 
  scale_colour_manual(values = c("#1b9e77", "#d95f02", "#7570b3")) +
  coord_equal() + 
  theme_light() + 
  xlab(paste0("PC1 (", signif(pve$pve[1], 3), "%)")) + 
  ylab(paste0("PC3 (", signif(pve$pve[2], 3), "%)")) +
  ggtitle("PC 1 + PC 3")

print(b)
```

# ADMIXTURE Results

Directions from [this site](https://owensgl.github.io/biol525D/Topic_8-9/plotting_structure.html).

```{r}
samplelist <- read_tsv("~/Documents/GitHub/rift_birds/chamaetylas.txt",col_names = "sample")

read_delim("~/Documents/06_plink/chamaetylas_nothin_plink.5.Q",col_names = paste0("Q",seq(1:6)),
           delim = " ")
```

```{r, eval=F}
cv <- c(1.24030, 2.46934, 2.49640,
        2.78206, 0.92918, 0.35207)

k <- 1:6

cv_tab <- cbind(cv,k) %>% as.data.frame()

ggplot(cv_tab,aes(x = k, y = cv)) +
  geom_line()
```


```{r}
all_data <- tibble(sample=character(),
                   k=numeric(),
                   Q=character(),
                   value=numeric())

for (k in c(2:5)){
  data <- read_delim(paste0("~/Documents/06_plink/chamaetylas_nothin_plink.",k,".Q"),
                  col_names = paste0("Q",seq(1:k)),
                  delim=" ")
  data$sample <- samplelist$sample
  data$k <- k
  
  #This step converts from wide to long.
  data %>% gather(Q, value, -sample,-k) -> data
  all_data <- rbind(all_data,data)
}
```
```{r}
all_data %>%
  filter(k == 2) %>%
  ggplot(.,aes(x=sample,y=value,fill=factor(Q))) + 
  geom_bar(stat="identity",position="stack") +
  xlab("Sample") + ylab("Ancestry") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 60, hjust = 1)) +
  scale_fill_brewer(palette="Set1",name="K",
                    labels=c("1","2"))
```


```{r}
all_data %>%
  filter(k == 3) %>%
  ggplot(.,aes(x=sample,y=value,fill=factor(Q))) + 
  geom_bar(stat="identity",position="stack") +
  xlab("Sample") + ylab("Ancestry") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 60, hjust = 1)) +
  scale_fill_brewer(palette="Set1",name="K",
                    labels=c("1","2", "3"))
```

```{r}
all_data %>%
  filter(k == 4) %>%
  ggplot(.,aes(x=sample,y=value,fill=factor(Q))) + 
  geom_bar(stat="identity",position="stack") +
  xlab("Sample") + ylab("Ancestry") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 60, hjust = 1)) +
  scale_fill_brewer(palette="Set1",name="K",
                    labels=c("1","2", "3", "4"))
```

```{r}
all_data %>%
  filter(k == 5) %>%
  ggplot(.,aes(x=sample,y=value,fill=factor(Q))) + 
  geom_bar(stat="identity",position="stack") +
  xlab("Sample") + ylab("Ancestry") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 60, hjust = 1)) +
  scale_fill_brewer(palette="Set1",name="K",
                    labels=c("1","2", "3", "4", "5"))
```

